[package]
name = "fang"
version = "0.10.2"
authors = [
    "Ayrat Badykov <ayratin555@gmail.com>",
    "Pepe Márquez <pepe.marquezromero@gmail.com>",
    "Rafael Caricio <rafael@caricio.com>"
]
description = "Background job processing library for Rust"
repository = "https://github.com/rafaelcaricio/fang"
edition = "2021"
license = "MIT"
readme = "README.md"
rust-version = "1.67"

[lib]
doctest = false

[dependencies]
cron = "0.12"
chrono = "0.4"
hex = "0.4"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.10"
thiserror = "1.0"
typed-builder = "0.12"
typetag = "0.2"
uuid = { version = "1.1", features = ["v4"] }

[dependencies.diesel]
version = "2.0"
features = ["postgres", "serde_json", "chrono", "uuid", "r2d2"]

[dependencies.diesel-derive-enum]
version = "2.0.1"
features = ["postgres"]

[dependencies.diesel-async]
version = "0.2"
features = ["postgres", "bb8"]

[dependencies.tokio]
version = "1.25"
features = ["rt", "time", "macros"]

[dependencies.async-trait]
version = "0.1"

[dependencies.async-recursion]
version = "1"
